name: Build and push Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        gcc-version:
          - "15.2.0"
          - "14.3.0"
          - "13.4.0"
          - "12.5.0"
          - "11.5.0"
          - "10.5.0"
          - "9.5.0"
        base-image-tag:
          - trixie
          - bookworm
          - bullseye
          - noble
          - jammy
          - focal
          - bionic
          - xenial
    uses: ./.github/workflows/docker-build.yml
    with:
      gcc-version: ${{ matrix.gcc-version }}
      base-image-tag: ${{ matrix.base-image-tag }}
    secrets: inherit
