name: Build and push Docker images for a GCC version and base image

on:
  workflow_call:
    inputs:
      gcc-version:
        type: string
      base-image-tag:
        type: string

concurrency:
  group: ${{ github.workflow }}-build-${{ inputs.gcc-version }}-${{ inputs.base-image-tag }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_USERNAME: zhongruoyu
  DOCKERHUB_REPOSITORY: zhongruoyu/gcc-ports
  GHCR_USERNAME: zhongruoyu
  GHCR_REPOSITORY: ghcr.io/zhongruoyu/gcc-ports

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    name: Build ${{ inputs.gcc-version }} - ${{ inputs.base-image-tag }} (${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
    env:
      GCC_VERSION: ${{ inputs.gcc-version }}
      BASE_IMAGE_TAG: ${{ inputs.base-image-tag }}
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Load build environment
        run: cat build.env >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ github.token }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          build-args: |
            BASE_IMAGE=public.ecr.aws/docker/library/buildpack-deps:${{ env.BASE_IMAGE_TAG }}
            GCC_VERSION
            BINUTILS_VERSION
          outputs: |
            type=image,name=${{ env.DOCKERHUB_REPOSITORY }},name-canonical=true,push=true,push-by-digest=true
            type=image,name=${{ env.GHCR_REPOSITORY }},name-canonical=true,push=true,push-by-digest=true
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP/digests/$GCC_VERSION-$BASE_IMAGE_TAG-$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ inputs.gcc-version }}-${{ inputs.base-image-tag }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*

  merge:
    needs: build
    name: Merge ${{ inputs.gcc-version }} - ${{ inputs.base-image-tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GCC_VERSION: ${{ inputs.gcc-version }}
      BASE_IMAGE_TAG: ${{ inputs.base-image-tag }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ github.token }}
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-${{ inputs.gcc-version }}-${{ inputs.base-image-tag }}-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create \
            --tag="$DOCKERHUB_REPOSITORY:$GCC_VERSION-$BASE_IMAGE_TAG" \
            --tag="$DOCKERHUB_REPOSITORY:$(echo "$GCC_VERSION" | cut -d '.' -f 1-2)-$BASE_IMAGE_TAG" \
            --tag="$DOCKERHUB_REPOSITORY:$(echo "$GCC_VERSION" | cut -d '.' -f 1)-$BASE_IMAGE_TAG" \
            --tag="$GHCR_REPOSITORY:$GCC_VERSION-$BASE_IMAGE_TAG" \
            --tag="$GHCR_REPOSITORY:$(echo "$GCC_VERSION" | cut -d '.' -f 1-2)-$BASE_IMAGE_TAG" \
            --tag="$GHCR_REPOSITORY:$(echo "$GCC_VERSION" | cut -d '.' -f 1)-$BASE_IMAGE_TAG" \
            "$GHCR_REPOSITORY@sha256:$(cat "$RUNNER_TEMP/digests/$GCC_VERSION-$BASE_IMAGE_TAG-x86_64")" \
            "$GHCR_REPOSITORY@sha256:$(cat "$RUNNER_TEMP/digests/$GCC_VERSION-$BASE_IMAGE_TAG-aarch64")"
