name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BINUTILS_VERSION: "2.44"

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        gcc-version:
          - "15.1.0"
          - "14.3.0"
          - "13.4.0"
          - "12.5.0"
          - "11.5.0"
          - "10.5.0"
          - "9.5.0"
        base-image-tag:
          - bookworm
          - bullseye
          - noble
          - jammy
          - focal
          - bionic
          - xenial
    name: ${{ matrix.gcc-version }} - ${{ matrix.base-image-tag }}
    env:
      BASE_IMAGE_TAG: ${{ matrix.base-image-tag }}
      GCC_VERSION: ${{ matrix.gcc-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine build attributes
        run: |
          cat <<EOF | tee -a "$GITHUB_ENV"
          GCC_VERSION_MAJOR=$(echo "${GCC_VERSION}" | cut -d '.' -f 1)
          GCC_VERSION_MAJOR_MINOR=$(echo "${GCC_VERSION}" | cut -d '.' -f 1-2)
          EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: |
            zhongruoyu/gcc-ports:${{ env.GCC_VERSION }}-${{ env.BASE_IMAGE_TAG }}
            zhongruoyu/gcc-ports:${{ env.GCC_VERSION_MAJOR_MINOR }}-${{ env.BASE_IMAGE_TAG }}
            zhongruoyu/gcc-ports:${{ env.GCC_VERSION_MAJOR }}-${{ env.BASE_IMAGE_TAG }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            GCC_VERSION=${{ env.GCC_VERSION }}
          push: true
