name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        gcc-version:
          - "16.1.0"
          - "15.2.0"
          - "14.3.0"
          - "13.4.0"
          - "12.5.0"
          - "11.5.0"
          - "10.5.0"
          - "9.5.0"
        base-image-tag:
          - trixie
          - bookworm
          - bullseye
          - resolute
          - noble
          - jammy
          - focal
          - bionic
          - xenial
    name: Build ${{ matrix.gcc-version }} - ${{ matrix.base-image-tag }}
    uses: ./.github/workflows/docker-build.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write # for pushing image and cache
    with:
      gcc-version: ${{ matrix.gcc-version }}
      base-image-tag: ${{ matrix.base-image-tag }}
      push: ${{ github.ref == 'refs/heads/main' }}
